{'code': 'rome_main_aquitania',
 'faction_stats': {'order_pct_foreign_culture': -20,
                   'research_pct': 8,
                   'research_pct_civil': 10,
                   'research_pct_military': 10,
                   'wealth_pct_agri': 20,
                   'wealth_pct_mining': 20,
                   'wealth_pct_mnfr': 20},
 'id': None,
 'name': 'Aquitania',
 'regions': [{'buildings': [{'code': 'barb_agriculture_cattle_4',
                             'cost': 4300,
                             'name': 'Cattle Ranch'},
                            {'code': 'barb_port_fishing_3',
                             'cost': 2300,
                             'name': 'Fishing Village'},
                            {'code': 'barb_military_buff_gold_3',
                             'cost': 5200,
                             'name': 'Enameller'},
                            {'code': 'barb_city_2',
                             'cost': 2700,
                             'name': 'Fortified Settlement'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'},
                            {'code': 'barb_religious_briton_nodens_3',
                             'cost': 2300,
                             'name': 'Shrine of Nodens'}],
              'code': 'rom_aquitania_aquitania',
              'name': 'Burdigala'},
             {'buildings': [{'code': 'barb_religious_briton_rosmerta_3',
                             'cost': 2700,
                             'name': 'Shrine of Rosmerta'},
                            {'code': 'barb_artisan_bronze_3',
                             'cost': 3000,
                             'name': 'Bronze Forge'},
                            {'code': 'barb_gold_2',
                             'cost': 3600,
                             'name': 'Village (Trench Mine)'}],
              'code': 'rom_aquitania_gergovia',
              'name': 'Nemossos'},
             {'buildings': [{'code': 'barb_iron_1',
                             'cost': 1000,
                             'name': 'Farmstead (Iron Workshop)'},
                            {'code': 'all_mine_3',
                             'cost': 3000,
                             'name': 'Shaft Mine'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'}],
              'code': 'rom_aquitania_pictavis',
              'name': 'Lemonum'}],
 'stats': {'food': 5,
           'wealth_livestock': 250,
           'wealth_mari_com': 50,
           'wealth_mining': 650,
           'wealth_mnfr': 720,
           'wealth_pct_all': 16,
           'wealth_pct_fun': 16,
           'wealth_pct_mining': 20,
           'wealth_subsistence': 300},
 'total_wealth': 2739.2}