 {'code': 'rome_main_belgica',
             'id': 18,
             'name': 'Belgica',
             'regions': [{'buildings': [{'code': 'barb_military_buff_gold_3',
                                         'cost': 5200,
                                         'name': 'Enameller'},
                                        {'code': 'barb_city_2',
                                         'cost': 2700,
                                         'name': 'Fortified Settlement'},
                                        {'code': 'barb_agriculture_cattle_4',
                                         'cost': 4300,
                                         'name': 'Cattle Ranch'},
                                        {'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'},
                                        {'code': 'barb_military_buff_grounds_3',
                                         'cost': 1700,
                                         'name': 'Proving Grounds'}],
                          'code': 'rom_belgica_silva_carbonaria',
                          'name': 'Nemetocenna'},
                         {'buildings': [{'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'},
                                        {'code': 'barb_horse_2',
                                         'cost': 2100,
                                         'name': 'Village (Horse Breeders)'},
                                        {'code': 'barb_artisan_bronze_3',
                                         'cost': 3000,
                                         'name': 'Bronze Forge'}],
                          'code': 'rom_belgica_arduenna_silva',
                          'name': 'Treverorum'}],
             'stats': {'food': -4,
                       'wealth_fun': 150,
                       'wealth_livestock': 450,
                       'wealth_mnfr': 620,
                       'wealth_pct_all': 8,
                       'wealth_pct_fun': 16,
                       'wealth_pct_mining': 20,
                       'wealth_subsistence': 300},
             'total_wealth': 1817.6},