{'code': 'rome_main_britannia',
  'id': 11,
  'name': 'Britannia',
  'regions': [{'buildings': [
    {'code': 'barb_religious_briton_toutatis_3',
    'cost': 2900,
    'name': 'Shrine of Toutatis'},
    {'code': 'barb_commons_slave_3',
      'cost': 11500,
      'name': 'Slave Market'},
    {'code': 'barb_port_fishing_3',
      'cost': 2300,
      'name': 'Fishing Village'},
    {'code': 'barb_city_2',
      'cost': 2700,
      'name': 'Fortified Settlement'},
    {'code': 'barb_religious_briton_rosmerta_3',
      'cost': 2700,
      'name': 'Shrine of Rosmerta'},
    {'code': 'barb_artisan_maker_3',
      'cost': 4100,
      'name': 'Trumpet Maker'}],
    'code': 'rom_britannia_britannia',
    'name': 'Camulodunon'},
    {'buildings': [{'code': 'barb_religious_briton_toutatis_3',
      'cost': 2900,
      'name': 'Shrine of Toutatis'},
      {'code': 'barb_leather_2',
        'cost': 1400,
        'name': 'Village (Open Air Tannery)'},
      {'code': 'barb_artisan_maker_3',
        'cost': 4100,
        'name': 'Trumpet Maker'}],
      'code': 'rom_britannia_brigantia',
      'name': 'Eborakon'},
    {'buildings': [{'code': 'barb_gold_2',
      'cost': 3600,
      'name': 'Village (Trench Mine)'},
      {'code': 'barb_port_fishing_3',
        'cost': 2300,
        'name': 'Fishing Village'},
      {'code': 'all_mine_3',
        'cost': 3000,
        'name': 'Shaft Mine'},
      {'code': 'barb_artisan_maker_3',
        'cost': 4100,
        'name': 'Trumpet Maker'}],
      'code': 'rom_britannia_demetia',
      'name': 'Moridunon'},
    {'buildings': [{'code': 'barb_port_fishing_3',
      'cost': 2300,
      'name': 'Fishing Village'},
      {'code': 'barb_town_2',
        'cost': 1800,
        'name': 'Village'},
      {'code': 'all_mine_3',
        'cost': 3000,
        'name': 'Shaft Mine'},
      {'code': 'barb_artisan_maker_3',
        'cost': 4100,
        'name': 'Trumpet Maker'}],
      'code': 'rom_britannia_dumnonia',
      'name': 'Iska'}],
  'stats': {'food': 2,
    'order': 1,
    'wealth_fun': 240,
    'wealth_local_com': 250,
    'wealth_mari_com': 150,
    'wealth_mining': 950,
    'wealth_mnfr': 790,
    'wealth_pct_agri': 20,
    'wealth_pct_all': 18,
    'wealth_pct_fun': 32,
    'wealth_pct_industry': 40,
    'wealth_subsistence': 400},
  'total_wealth': 4227.2}