{'code': 'rome_main_caledonia_et_hibernia',
             'id': 13,
             'name': 'Caledonia et Hibernia',
             'regions': [{'buildings': [{'code': 'barb_commons_market_3',
                                         'cost': 3600,
                                         'name': 'Public Market'},
                                        {'code': 'barb_agriculture_cattle_4',
                                         'cost': 4300,
                                         'name': 'Cattle Ranch'},
                                        {'code': 'barb_religious_briton_rosmerta_3',
                                         'cost': 2700,
                                         'name': 'Shrine of Rosmerta'},
                                        {'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'},
                                        {'code': 'barb_city_2',
                                         'cost': 2700,
                                         'name': 'Fortified Settlement'}],
                          'code': 'rom_caledonia_et_hibernia_caledonia',
                          'name': 'Eildon'},
                         {'buildings': [{'code': 'barb_town_2',
                                         'cost': 1800,
                                         'name': 'Village'},
                                        {'code': 'barb_agriculture_minor_cattle_4',
                                         'cost': 4300,
                                         'name': 'Cattle Ranch'},
                                        {'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'},
                                        {'code': 'barb_port_fishing_3',
                                         'cost': 2300,
                                         'name': 'Fishing Village'}],
                          'code': 'rom_caledonia_et_hibernia_hibernia',
                          'name': 'Eblana'}],
             'stats': {'food': 13,
                       'order': 1,
                       'wealth_livestock': 500,
                       'wealth_local_com': 160,
                       'wealth_mari_com': 50,
                       'wealth_mnfr': 320,
                       'wealth_pct_agri': 20,
                       'wealth_pct_all': 18,
                       'wealth_pct_fun': 16,
                       'wealth_subsistence': 400},
             'total_wealth': 1919.4},