{'code': 'rome_main_celtica',
 'faction_stats': {'order_pct_foreign_culture': -20,
                   'research_pct': 8,
                   'research_pct_civil': 10,
                   'research_pct_military': 10,
                   'wealth_pct_agri': 20,
                   'wealth_pct_mining': 10,
                   'wealth_pct_mnfr': 10},
 'id': None,
 'name': 'Celtica',
 'regions': [{'buildings': [{'code': 'barb_military_buff_gold_3',
                             'cost': 5200,
                             'name': 'Enameller'},
                            {'code': 'barb_city_2',
                             'cost': 2700,
                             'name': 'Fortified Settlement'},
                            {'code': 'barb_religious_briton_rosmerta_3',
                             'cost': 2700,
                             'name': 'Shrine of Rosmerta'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'},
                            {'code': 'barb_commons_lore_*',
                             'cost': 1300,
                             'name': "Loremaster's Hut"}],
              'code': 'rom_celtica_lugdunensis',
              'name': 'Bibracte'},
             {'buildings': [{'code': 'barb_religious_briton_rosmerta_3',
                             'cost': 2700,
                             'name': 'Shrine of Rosmerta'},
                            {'code': 'all_mine_3',
                             'cost': 3000,
                             'name': 'Shaft Mine'},
                            {'code': 'barb_port_fishing_3',
                             'cost': 2300,
                             'name': 'Fishing Village'},
                            {'code': 'barb_lumber_2',
                             'cost': 1600,
                             'name': 'Village (Logging Camp)'}],
              'code': 'rom_celtica_aremorica',
              'name': 'Namnetum'},
             {'buildings': [{'code': 'barb_town_2',
                             'cost': 1800,
                             'name': 'Village'},
                            {'code': 'barb_agriculture_minor_cattle_4',
                             'cost': 4300,
                             'name': 'Cattle Ranch'},
                            {'code': 'barb_craftsmen_wood_2',
                             'cost': 1700,
                             'name': 'Woodworker'}],
              'code': 'rom_celtica_lutetia',
              'name': 'Cenabum'}],
 'stats': {'food': 4,
           'wealth_learning': 70,
           'wealth_livestock': 250,
           'wealth_mari_com': 50,
           'wealth_mining': 300,
           'wealth_mnfr': 500,
           'wealth_pct_all': 26,
           'wealth_pct_fun': 8,
           'wealth_pct_industry': 10,
           'wealth_pct_mining': 20,
           'wealth_subsistence': 400},
 'total_wealth': 2248.2}