{'code': 'rome_main_germania_minor',
 'faction_stats': {'order_pct_foreign_culture': -20,
                   'research_pct': 8,
                   'research_pct_civil': 10,
                   'research_pct_military': 10,
                   'wealth_pct_agri': 20,
                   'wealth_pct_mining': 10,
                   'wealth_pct_mnfr': 10},
 'id': None,
 'name': 'Germania Minor',
 'regions': [{'buildings': [{'code': 'barb_religious_briton_rosmerta_3',
                             'cost': 2700,
                             'name': 'Shrine of Rosmerta'},
                            {'code': 'barb_artisan_bronze_3',
                             'cost': 3000,
                             'name': 'Bronze Forge'},
                            {'code': 'barb_city_2',
                             'cost': 2700,
                             'name': 'Fortified Settlement'},
                            {'code': 'barb_agriculture_cattle_4',
                             'cost': 4300,
                             'name': 'Cattle Ranch'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'}],
              'code': 'rom_germania_minor_germania_superior',
              'name': 'Vesontio'},
             {'buildings': [{'code': 'barb_agriculture_cattle_4',
                             'cost': 4300,
                             'name': 'Cattle Ranch'},
                            {'code': 'barb_glass_2',
                             'cost': 1400,
                             'name': 'Village (Glass Blower)'},
                            {'code': 'all_mine_3',
                             'cost': 3000,
                             'name': 'Shaft Mine'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'}],
              'code': 'rom_germania_minor_germania_inferior',
              'name': 'Bagacum'}],
 'stats': {'food': 6,
           'order': 1,
           'wealth_livestock': 500,
           'wealth_mining': 300,
           'wealth_mnfr': 570,
           'wealth_pct_all': 16,
           'wealth_pct_fun': 16,
           'wealth_subsistence': 300},
 'total_wealth': 2124.2}