{'code': 'rome_main_germania_minor',
             'id': 17,
             'name': 'Germania Minor',
             'regions': [{'buildings': [{'code': 'barb_commons_market_3',
                                         'cost': 3600,
                                         'name': 'Public Market'},
                                        {'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'},
                                        {'code': 'barb_agriculture_cattle_4',
                                         'cost': 4300,
                                         'name': 'Cattle Ranch'},
                                        {'code': 'barb_religious_briton_toutatis_3',
                                         'cost': 2900,
                                         'name': 'Shrine of Toutatis'},
                                        {'code': 'barb_city_2',
                                         'cost': 2700,
                                         'name': 'Fortified Settlement'}],
                          'code': 'rom_germania_minor_germania_superior',
                          'name': 'Vesontio'},
                         {'buildings': [{'code': 'barb_glass_2',
                                         'cost': 1400,
                                         'name': 'Village (Glass Blower)'},
                                        {'code': 'barb_agriculture_minor_cattle_4',
                                         'cost': 4300,
                                         'name': 'Cattle Ranch'},
                                        {'code': 'barb_artisan_maker_3',
                                         'cost': 4100,
                                         'name': 'Trumpet Maker'}],
                          'code': 'rom_germania_minor_germania_inferior',
                          'name': 'Bagacum'}],
             'stats': {'food': 4,
                       'order': 1,
                       'wealth_fun': 120,
                       'wealth_livestock': 500,
                       'wealth_local_com': 160,
                       'wealth_mnfr': 470,
                       'wealth_pct_agri': 20,
                       'wealth_pct_all': 8,
                       'wealth_pct_fun': 16,
                       'wealth_pct_industry': 10,
                       'wealth_subsistence': 300},
             'total_wealth': 1987.2}