{'code': 'rome_main_magna_germania',
 'faction_stats': {'order_pct_foreign_culture': -20,
                   'research_pct': 8,
                   'research_pct_civil': 10,
                   'research_pct_military': 10,
                   'wealth_pct_agri': 20,
                   'wealth_pct_mining': 10,
                   'wealth_pct_mnfr': 20},
 'id': None,
 'name': 'Magna Germania',
 'regions': [{'buildings': [{'code': 'barb_commons_slave_3',
                             'cost': 11500,
                             'name': 'Slave Market'},
                            {'code': 'barb_religious_briton_toutatis_3',
                             'cost': 2900,
                             'name': 'Shrine of Toutatis'},
                            {'code': 'barb_religious_briton_rosmerta_3',
                             'cost': 2700,
                             'name': 'Shrine of Rosmerta'},
                            {'code': 'barb_city_2',
                             'cost': 2700,
                             'name': 'Fortified Settlement'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'}],
              'code': 'rom_magna_germania_silva_bacenis',
              'name': 'Tulifurdum'},
             {'buildings': [{'code': 'all_mine_3',
                             'cost': 3000,
                             'name': 'Shaft Mine'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'},
                            {'code': 'barb_port_fishing_3',
                             'cost': 2300,
                             'name': 'Fishing Village'},
                            {'code': 'barb_town_2',
                             'cost': 1800,
                             'name': 'Village'}],
              'code': 'rom_magna_germania_frisia',
              'name': 'Flevum'},
             {'buildings': [{'code': 'all_mine_3',
                             'cost': 3000,
                             'name': 'Shaft Mine'},
                            {'code': 'barb_leather_2',
                             'cost': 1400,
                             'name': 'Village (Open Air Tannery)'},
                            {'code': 'barb_artisan_maker_3',
                             'cost': 4100,
                             'name': 'Trumpet Maker'}],
              'code': 'rom_magna_germania_silva_nigra',
              'name': 'Uburzis'}],
 'stats': {'food': -8,
           'order': 3,
           'wealth_fun': 120,
           'wealth_local_com': 250,
           'wealth_mari_com': 50,
           'wealth_mining': 600,
           'wealth_mnfr': 630,
           'wealth_pct_agri': 20,
           'wealth_pct_all': 18,
           'wealth_pct_fun': 24,
           'wealth_pct_industry': 30,
           'wealth_subsistence': 400},
 'total_wealth': 3002.7999999999997}